# The `rstats` service
This service is based on the `rocker/rstudio` image from Docker Hub: <https://hub.docker.com/r/rocker/rstudio/>, [@Boettiger2015]. I've added header files so that the R packages I use regularly will install from source, but there are no R packages on the image besides those that ship with `rocker/rstudio`.

Browse to `localhost:8787`. The user name is `rstudio` and the password is the value of `PASSWORD` you set in `.env`.

## Setting up `git`
1. Edit `configure-git.bash`. You'll need to supply your email address and name.
2. Open a new terminal and enter `scripts/configure-git.bash`.

To clone a repository, use its `https` URL. For a private repository, you'll need to authenticate when you clone. For a public one, you'll only have to authenticate if you want to push.

In either case, once you've authenticated, `git` will cache your credentials for an hour. As you probably noticed, this timeout is adjustable in `configure-git.bash`.

Cloning this repository:

1. Open a new terminal and enter `scripts/clone-me.bash`.

You will find the repository in `$HOME/Projects/data-science-pet-containers`

## Installing R packages
As noted above, to keep the image size down, I've only installed header files so that the R packages I use regularly will install. That covers the majority of use cases.

I've put scripts to install "task views" in the `scripts` folder. I use these to test the image / service. They do tend to run long, ao only run them if you're working in the area they cover. Otherwise, just install what you want. If RStudio finds it needs a package, it will prompt you to install it.

If you find an R package that won't install because of missing header or other Linux dependency, open an issue at <https://github.com/znmeb/data-science-pet-containers/issues/new>. 

Most common R packages that fail to install because of missing dependencies will list the name of the Debian packages you need to install. If that's the case, open a `root` console from a ***host*** terminal with `docker exec -it -u root containers_rstats_1 /bin/bash`. Then type `apt install <package-name>`. After the Debian package is installed, you should be able to install the R package.

## Connecting to the `postgis` service
To connect to the `postgis` service, use the host name `postgis` and port `5432`. The user name, password and database name (`dbname`) must be valid in the database.
