# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias l='ls --color=auto -CFtr'
alias la='ls --color=auto -A'
alias ll='ls --color=auto -Altr'
alias up='sudo docker-compose up -d --build'
alias down='sudo docker-compose down'
alias stop='sudo docker-compose stop'
export VISUAL=/usr/bin/vim
export EDITOR=/usr/bin/vim
ulimit -s 32768
