FROM postgres:11
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

# Install apt packages
RUN apt-get update \
  && apt-get install -qqy --no-install-recommends \
    postgresql-11-ogr-fdw \
    postgresql-11-pgrouting \
    postgresql-11-pgrouting-doc \
    postgresql-11-pgrouting-scripts \
    postgresql-11-plr \
    postgresql-11-postgis-2.5 \
    postgresql-11-postgis-2.5-scripts \
    postgresql-11-postgis-scripts \
    postgresql-client-11 \
  && apt-get clean
