FROM registry.fedoraproject.org/fedora:39
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

# passwordless sudo
#COPY 10-installer /etc/sudoers.d/

# Fedora packages
RUN dnf upgrade -y \
  && dnf install -y \
     R-devel \
     R-devtools \
     R-flexiblas \
     gcc-c++ \
     gcc-gfortran \
     git-lfs \
     rstudio-server \
     vim
